using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace FocusFlowFinal.Services;

public class LocalizationService : ObservableObject
{
    private static readonly Lazy<LocalizationService> _instance = new(() => new LocalizationService());
    public static LocalizationService Instance => _instance.Value;

    private string _currentLanguage = "Русский";
    private readonly Dictionary<string, Dictionary<string, string>> _translations;

    private LocalizationService()
    {
        _translations = new Dictionary<string, Dictionary<string, string>>
        {
            ["Русский"] = new Dictionary<string, string>
            {
                // Окно настроек
                ["Settings"] = "Настройки",
                ["General"] = "Общие",
                ["Notifications"] = "Уведомления",
                ["Hotkeys"] = "Горячие клавиши",
                ["Data"] = "Данные",
                ["Appearance"] = "🌙 Внешний вид",
                ["LightTheme"] = "Светлая",
                ["DarkTheme"] = "Тёмная",
                ["AutoTheme"] = "Авто",
                ["LangRegion"] = "🌐 Язык и регион",
                ["SysNotif"] = "Системные уведомления",
                ["SysNotifSub"] = "Показывать уведомления в системе",
                ["SoundNotif"] = "Звуковые уведомления",
                ["SoundNotifSub"] = "Воспроизводить звук при окончании таймера",
                ["SwitchToDay"] = "Переключить на День",
                ["SwitchToWeek"] = "Переключить на Неделю",
                ["SwitchToMonth"] = "Переключить на Месяц",
                ["SwitchToYear"] = "Переключить на Год",
                ["GoToToday"] = "Перейти на сегодня",
                ["NewTask"] = "Новая задача",
                ["ExportData"] = "💾 Импорт и экспорт данных",
                ["Backup"] = "Резервное копирование",
                ["BackupSub"] = "Создайте резервную копию всех ваших задач",
                ["ExportBtn"] = "Экспортировать",
                ["ExportSuccess"] = "Данные успешно экспортированы!",
                ["ExportError"] = "Ошибка при экспорте данных: ",
                ["DangerZone"] = "Опасная зона",
                ["ClearSub"] = "Удаление всех данных без восстановления",
                ["ClearBtn"] = "Очистить все данные",
                ["ClearConfirm"] = "Вы уверены? Все данные будут удалены без возможности восстановления.",
                ["Yes"] = "Да",
                ["No"] = "Нет",
                ["ClearSuccess"] = "Все данные удалены.",
                ["Close"] = "Закрыть",
                ["Save"] = "Сохранить",

                // Главное окно
                ["TitleDay"] = "День",
                ["TitleWeek"] = "Неделя",
                ["TitleMonth"] = "Месяц",
                ["TitleYear"] = "Год",
                ["Tasks"] = "Задачи",
                ["Timer"] = "Таймер",
                ["AnalyticsTitle"] = "Аналитика",
                ["MoreBtn"] = "Подробнее",
                ["CustomSettings"] = "Свои настройки",
                ["FilterAll"] = "Все",
                ["FilterHigh"] = "Высокий",
                ["FilterMedium"] = "Средний",
                ["AddEventBtn"] = "+ Событие",
                ["TodayBtn"] = "Сегодня",

                ["AnalyticsSubtitle"] = "Детальный отчет за текущий период",
                ["FocusedTotal"] = "Всего сфокусирован",
                ["TasksCompleted"] = "Задач завершено",
                ["Productivity"] = "Продуктивность",
                ["FocusDistributionWeek"] = "Распределение фокуса по дням недели",
                ["ProjectFocusCategories"] = "Фокус по категориям проектов",
                ["Done"] = "Готово",
                ["LowLevel"] = "Низкий уровень",
                ["MediumLevel"] = "Средний уровень",
                ["HighLevel"] = "Высокий уровень",

                ["PlanVsFactToday"] = "План vs Факт сегодня",
                ["MoreDetails"] = "Подробнее",
                ["Plan"] = "План",
                ["Fact"] = "Факт",
                ["CustomMode"] = "Пользовательский режим",
                ["Week"] = "Неделя",
                ["HoursShort"] = "ч",
                ["MinutesShort"] = "м",
                // ИСПРАВЛЕНО: полные обозначения для DurationText ("30 мин", "1 ч 15 мин")
                ["DurationMin"] = "мин",
                ["DurationHour"] = "ч",
                ["PerWeek"] = "за неделю",
                ["Deviation"] = "Отклонение",
                ["NoProject"] = "Без проекта",

                // ИСПРАВЛЕНО: новые ключи локализации (фильтры, проекты, готово, выполненные задачи)
                ["AllProjectsLbl"] = "Все проекты",
                ["AllFilter"] = "Все",
                ["ActiveFilter"] = "Активные",
                ["CompletedFilter"] = "Выполненные",
                ["DoneBtn"] = "Готово",
                ["CompletedTasksHeader"] = "Выполненные задачи",
                ["PrevWeekTip"] = "Предыдущая неделя",
                ["NextWeekTip"] = "Следующая неделя",
                ["DeviationLabel"] = "План / Факт (сегодня)",
                ["DeviationSubNoPlan"] = "Нет задач на сегодня",
                ["DeviationSubUnder"] = "Недовыполнение",
                ["DeviationSubOnTrack"] = "В плане",

                // Шаблоны Помодоро
                ["PomodoroTemplates"] = "Шаблоны Помодоро",
                ["SaveAsTemplate"] = "Сохранить как шаблон",
                ["TemplateName"] = "Имя шаблона",
                ["WorkTime"] = "Работа",
                ["BreakTime"] = "Отдых",

                // Окна создания
                ["TaskTitle"] = "Задача",
                ["TaskNameLbl"] = "Название задачи:",
                ["TaskDesc"] = "Описание:",
                ["DueDateLabel"] = "Срок выполнения:",
                ["PriorityLabel"] = "Приоритет:",
                ["TaskNameWatermark"] = "Введите название задачи",
                ["TaskDescWatermark"] = "Добавьте описание",
                ["HasDateOpt"] = "📅 Назначить дату дедлайна",
                ["IsTimeBoundOpt"] = "⏰ Привязать к конкретному времени",
                ["IsDurationOpt"] = "📊 Установить длительность",
                ["DurationLabel"] = "Продолжительность (мин):",
                ["FilterLow"] = "Низкий",
                ["ProjectLabel"] = "📁 Проект:",
                ["EventTitle"] = "Событие",
                ["AllDayLbl"] = "Весь день",
                ["StartTimeLbl"] = "Время начала:",
                ["EndTimeLbl"] = "Время окончания:",
                ["HourLabel"] = "Час:",
                ["MinLabel"] = "Мин:",
                ["ColorLabel"] = "Цвет:",
                ["HexColorLabel"] = "HEX код:",
                ["WorkingDaysLbl"] = "Количество рабочих дней:",
                ["OffDaysLbl"] = "Количество выходных дней:",
                ["CycleStartLabel"] = "Начальная дата цикла:",
                ["IntervalLabel"] = "Интервал (каждые N):",
                ["IntervalUnitLbl"] = "Единица измерения:",

                // Выбор дня начала повторения
                ["MonthlyDayLbl"] = "День месяца (1-31):",
                ["YearlyDayLbl"] = "День:",
                ["YearlyMonthLbl"] = "Месяц (1-12):",
                ["RecurrenceStartDayHint"] = "День начала повторения",

                // Локализация типов повторения
                ["RecurrenceLbl"] = "Повторение:",
                ["Recurrence_None"] = "Без повторения",
                ["Recurrence_Daily"] = "Каждый день",
                ["Recurrence_Weekdays"] = "По рабочим дням",
                ["Recurrence_Weekly"] = "По дням недели",
                ["Recurrence_Monthly"] = "Каждый месяц",
                ["Recurrence_Yearly"] = "Каждый год",
                ["Recurrence_Shift"] = "График сменности (2/2)",
                ["Recurrence_Custom"] = "Свой интервал",

                // Локализация единиц интервала
                ["IntervalUnit_Days"] = "Дней",
                ["IntervalUnit_Weeks"] = "Недель",
                ["IntervalUnit_Months"] = "Месяцев",

                // Локализация дней недели в диалоге
                ["Day_Mon"] = "Пн",
                ["Day_Tue"] = "Вт",
                ["Day_Wed"] = "Ср",
                ["Day_Thu"] = "Чт",
                ["Day_Fri"] = "Пт",
                ["Day_Sat"] = "Сб",
                ["Day_Sun"] = "Вс",

                // Метка даты окончания повторений
                ["RepeatUntilLbl"] = "Повторять до",
                // ИСПРАВЛЕНО (4.4): локализованное имя стандартного таймера
                ["PomodoroDefault"] = "Помодоро 25/5",
                // ИСПРАВЛЕНО (4.1): watermark-подсказки для EventDialog
                ["EventNameWatermark"] = "Введите название события",
                ["EventDescriptionWatermark"] = "Добавьте описание (необязательно)",
                ["HexColorWatermark"] = "HEX-код цвета, например #3B82F6",
                // ИСПРАВЛЕНО (4.5): управление шаблонами таймера
                ["DeleteTemplateConfirm"] = "Удалить этот шаблон?",
                ["TemplatesHeader"] = "Шаблоны таймера",

                // ИСПРАВЛЕНО (Часть 2-3): аккаунт, вход, регистрация, подписка
                ["Account"] = "Аккаунт",
                ["LoginTitle"] = "Вход в FocusFlow",
                ["LoginEmailLbl"] = "Email",
                ["LoginPasswordLbl"] = "Пароль",
                ["LoginBtn"] = "Войти",
                ["RegisterLinkBtn"] = "Создать аккаунт",
                ["ContinueWithoutSyncBtn"] = "Продолжить без синхронизации",
                ["RegisterTitle"] = "Регистрация",
                ["RegisterUsernameLbl"] = "Имя пользователя",
                ["RegisterConfirmPasswordLbl"] = "Подтверждение пароля",
                ["RegisterBtn"] = "Зарегистрироваться",
                ["BackToLoginBtn"] = "Назад ко входу",
                ["AuthFillAllFields"] = "Заполните все поля",
                ["AuthEmailTaken"] = "Пользователь с таким email уже существует",
                ["AuthInvalidCredentials"] = "Неверный email или пароль",
                ["AuthNotLoggedIn"] = "Вы не вошли в аккаунт",
                ["AuthWrongPassword"] = "Неверный текущий пароль",
                ["PasswordsDontMatch"] = "Пароли не совпадают",
                ["PaymentInvalidPlan"] = "Неизвестный тарифный план",
                ["PerMonth"] = "мес",
                ["PerYear"] = "год",
                ["SubscriptionRequiredTitle"] = "Синхронизация недоступна",
                ["SubscriptionRequiredText"] = "Для использования синхронизации и управления аккаунтом приобретите подписку",
                ["BuyMonthBtn"] = "Купить месяц",
                ["BuyYearBtn"] = "Купить год",
                ["SubscriptionActiveLbl"] = "Подписка активна до",
                ["DeveloperModeLbl"] = "Режим разработчика — бесплатный доступ",
                ["FreeAccessLbl"] = "Бесплатный доступ предоставлен",
                ["SyncNowBtn"] = "Синхронизировать сейчас",
                ["SyncEnabledLbl"] = "Использовать синхронизацию",
                ["LastSyncLbl"] = "Последняя синхронизация",
                ["NeverLbl"] = "никогда",
                ["LogoutBtn"] = "Выйти из аккаунта",
                ["EditProfileUsername"] = "Имя пользователя",
                ["EditProfileEmail"] = "Email",
                ["ChangePasswordBtn"] = "Изменить пароль",
                ["CurrentPasswordLbl"] = "Текущий пароль",
                ["NewPasswordLbl"] = "Новый пароль",
                ["SyncingNowLbl"] = "Синхронизация...",
                ["SyncSuccessLbl"] = "Синхронизация завершена",
                ["SyncFailedLbl"] = "Не удалось синхронизировать — сервер недоступен",
                ["PostPurchaseTitle"] = "Подписка активирована!",
                ["PostPurchaseText"] = "Создайте аккаунт или войдите в существующий, чтобы начать синхронизацию",
                ["AlreadyHaveAccountBtn"] = "У меня уже есть аккаунт",
                ["CreateAccountBtn"] = "Создать аккаунт",
                ["ChooseAvatarBtn"] = "Выбрать фото",
                ["RepeatUntilHint"] = "Выберите дату окончания",

                // EventDialog хардкодные строки
                ["LoadTemplateHint"] = "Загрузить из шаблона:",
                ["ChooseTemplate"] = "Выберите шаблон...",
                ["EventNameLbl"] = "Название:",
                ["SaveAsTemplateLbl"] = "Сохранить как шаблон",
                ["TemplateNameWatermark"] = "Название шаблона",
                ["TemplateHint"] = "Шаблон появится в менеджере шаблонов",
                ["DeleteBtn"] = "Удалить",
                ["CancelBtn"] = "Отмена",
                ["SaveBtn"] = "Сохранить",
                ["DaysLbl"] = "Дни:",
                ["CycleStartLbl"] = "Начало цикла:",
                ["IntervalLbl"] = "Интервал (каждые N):",

                // Горячие клавиши (описания в Settings)
                ["HotkeyDay"] = "Переключить на День",
                ["HotkeyWeek"] = "Переключить на Неделю",
                ["HotkeyMonth"] = "Переключить на Месяц",
                ["HotkeyYear"] = "Переключить на Год",
                ["HotkeyNewTask"] = "Новая задача",
                ["HotkeyToday"] = "Перейти на сегодня",

                // Уведомления
                ["NotifEventTitle"] = "Напоминание о событии",
                ["NotifTimerTitle"] = "Таймер завершён",
                ["NotifTimerBody"] = "Сессия Помодоро завершена. Сделайте перерыв!",
                ["MarkTaskOnTimerFinish"] = "Автовыполнение задачи",
                ["MarkTaskOnTimerFinishSub"] = "Отмечать задачу выполненной по окончании всех циклов таймера",

                // Для годового календаря
                ["YearWord"] = "год",
                ["January"] = "Январь",
                ["February"] = "Февраль",
                ["March"] = "Март",
                ["April"] = "Апрель",
                ["May"] = "Май",
                ["June"] = "Июнь",
                ["July"] = "Июль",
                ["August"] = "Август",
                ["September"] = "Сентябрь",
                ["October"] = "Октябрь",
                ["November"] = "Ноябрь",
                ["December"] = "Декабрь",
                ["MonShort"] = "Пн",
                ["TueShort"] = "Вт",
                ["WedShort"] = "Ср",
                ["ThuShort"] = "Чт",
                ["FriShort"] = "Пт",
                ["SatShort"] = "Сб",
                ["SunShort"] = "Вс",

                // Горячие клавиши Info
                ["HotkeyCtrl1"] = "Ctrl + 1",
                ["HotkeyCtrl2"] = "Ctrl + 2",
                ["HotkeyCtrlM"] = "Ctrl + M",
                ["HotkeyCtrlY"] = "Ctrl + Y",
                ["HotkeyCtrlN"] = "Ctrl + N",
                ["HotkeyCtrlT"] = "Ctrl + T",

                // Подзадачи
                ["SubtasksLabel"]    = "Подзадачи",
                ["SubtaskWatermark"] = "Название подзадачи",
                ["AddSubtaskBtn"]    = "+ Добавить подзадачу",

                // Диалог завершения таймера
                ["TimerDoneTitle"]       = "Таймер завершён",
                ["TimerDoneQuestion"]    = "Задача выполнена?",
                ["TimerDoneOptions"]                = "Что сделать с задачей?",
                ["TimerExtendLabel"]               = "Продлить на",
                ["TimerExtendMinSuffix"]            = "мин",
                ["TimerCompletion_ExtendWatermark"] = "Минуты",
                ["TimerExtendError"]               = "Введите целое число ≥ 1",
                ["TimerExtendBtn"]                 = "Продлить таймер",
                ["TimerDeferBtn"]        = "Отложить задачу",
                ["TimerDeleteTaskBtn"]   = "Удалить задачу",

                // Уведомления событий с отступом
                ["NotifTimeLbl"]         = "Уведомить заранее:",
                ["Notif_None"]           = "Не уведомлять",
                ["Notif_10min"]          = "За 10 минут",
                ["Notif_30min"]          = "За 30 минут",
                ["Notif_1hour"]          = "За 1 час",
                ["Notif_1day"]           = "За 1 день",
                ["NotifOffset_soon"]     = "скоро начинается",
                ["NotifOffset_30min"]    = "через 30 мин",
                ["NotifOffset_1hour"]    = "через 1 час",
                ["NotifOffset_1day"]     = "завтра",
                ["StartsNow"]            = "начинается сейчас",

                // Копирование событий
                ["CopyEventBtn"]         = "Создать копии на дни",
                ["CopyEventTitle"]       = "Выберите дни для копий",
                ["CopyApplyBtn"]         = "Создать копии",
                ["CopySelectedCount"]    = "Выбрано дней:",
                ["CopySuccess"]          = "Копии событий созданы",
                ["CopyPrevMonth"]        = "< Назад",
                ["CopyNextMonth"]        = "Далее >",

                // Финансовый модуль
                ["Finance"]              = "Финансы",
                ["FinanceModuleLbl"]     = "Финансовый модуль",
                ["FinanceModuleSub"]     = "Учёт доходов, расходов, подписок и кредитов",
                ["FinanceTab_Income"]    = "Доходы",
                ["FinanceTab_Expense"]   = "Расходы",
                ["FinanceTab_Sub"]       = "Подписки",
                ["FinanceTab_Loans"]     = "Кредиты",
                ["FinanceTab_Summary"]   = "Сводка",
                ["Finance_AddIncome"]    = "+ Доход",
                ["Finance_AddExpense"]   = "+ Расход",
                ["Finance_AddSub"]       = "+ Подписка",
                ["Finance_AddLoan"]      = "+ Кредит",
                ["Finance_DateLbl"]      = "Дата:",
                ["Finance_CategoryLbl"]  = "Категория:",
                ["Finance_AmountLbl"]    = "Сумма (₽):",
                ["Finance_NoteLbl"]      = "Примечание:",
                ["Finance_NameLbl"]      = "Название:",
                ["Finance_CycleLbl"]     = "Периодичность:",
                ["Finance_NextDateLbl"]  = "Следующая дата списания:",
                ["Finance_PaidLbl"]      = "Оплачено",
                ["Finance_TotalLbl"]     = "Сумма кредита:",
                ["Finance_RateLbl"]      = "Процентная ставка (% год):",
                ["Finance_TermLbl"]      = "Срок (мес):",
                ["Finance_MonthlyLbl"]   = "Ежемесячный платёж:",
                ["Finance_RemainLbl"]    = "Остаток долга:",
                ["Finance_StartDateLbl"] = "Дата выдачи:",
                ["Finance_Balance"]      = "Баланс",
                ["Finance_TotalIncome"]  = "Доходы за месяц",
                ["Finance_TotalExpense"] = "Расходы за месяц",
                ["Finance_Monthly"]      = "Ежемесячно",
                ["Finance_Yearly"]       = "Ежегодно",
                ["Finance_ExportExcel"]  = "📊 Экспорт в Excel",
                ["Finance_CalcPayment"]  = "Рассчитать",
                ["Finance_EditBtn"]      = "✏",
                ["Finance_DeleteBtn"]    = "✕",
                ["Finance_SaveBtn"]      = "Сохранить",
                ["Finance_CancelBtn"]    = "Отмена",
                ["Finance_CatSalary"]    = "Зарплата",
                ["Finance_CatFreelance"] = "Фриланс",
                ["Finance_CatOther"]     = "Прочее",
                ["Finance_CatFood"]      = "Еда",
                ["Finance_CatTransport"] = "Транспорт",
                ["Finance_CatEntertain"] = "Развлечения",
                ["Finance_CatHealth"]    = "Здоровье",
                ["Finance_CatHousing"]   = "Жильё",
                ["Finance_CatStreaming"]  = "Стриминг",
                ["Finance_CatSoftware"]  = "ПО / Сервисы",
                ["Finance_CatMortgage"]        = "Ипотека",
                ["Finance_CatCar"]             = "Автокредит",
                ["Finance_CatConsumer"]        = "Потребительский",
                ["Finance_AmountRequired"]     = "Введите сумму больше 0",
                ["Finance_AddCategory"]        = "+ Категория",
                ["Finance_NewCategoryLbl"]     = "Новая категория:",
                ["Finance_DownPaymentLbl"]     = "Первоначальный взнос:",
                ["Finance_TermYearsLbl"]       = "Срок (лет):",
                ["Finance_NextPaymentLbl"]     = "Следующий платёж:",
                ["Finance_EndDateLbl"]         = "Дата окончания:",
                ["Finance_NotifDaysLbl"]       = "Уведомить за (дн):",
                ["Finance_EarlyRepayments"]    = "Досрочные погашения",
                ["Finance_AddRepayment"]       = "+ Погашение",
                ["Finance_PaymentDue"]         = "платёж через",
                ["Finance_EnabledInSettings"]  = "Включить в Настройки → Функции",

                // Подсказки "список пуст"
                ["Finance_IncomesEmptyHint"]   = "Нет доходов. Нажмите «+ Доход» чтобы добавить.",
                ["Finance_ExpensesEmptyHint"]  = "Нет расходов. Нажмите «+ Расход» чтобы добавить.",
                ["Finance_SubsEmptyHint"]      = "Нет подписок. Нажмите «+ Подписка» чтобы добавить.",
                ["Finance_LoansEmptyHint"]     = "Нет кредитов. Нажмите «+ Кредит» чтобы добавить.",

                // История счёта (toggle)
                ["Savings_ShowHistory"]        = "▼ История",
                ["Savings_HideHistory"]        = "▲ Скрыть историю",

                // Сводка — детали по секциям
                ["Summary_IncomeCount"]        = "Записей:",
                ["Summary_ExpenseCount"]       = "Записей:",
                ["Summary_SubCount"]           = "Подписок:",
                ["Summary_SubMonthly"]         = "В месяц:",
                ["Summary_LoanCount"]          = "Кредитов:",
                ["Summary_LoanDebt"]           = "Общий долг:",
                ["Summary_LoanMonthly"]        = "Платёж/мес:",

                // Копилки / Сберегательные счета
                ["FinanceTab_Savings"]         = "Счета/Копилки",
                ["Savings_AddAccount"]         = "+ Счёт",
                ["Savings_AddGoal"]            = "+ Копилка",
                ["Savings_NewAccount"]         = "Новый счёт",
                ["Savings_NewGoal"]            = "Новая копилка",
                ["Savings_GoalBadge"]          = "🎯 Копилка",
                ["Savings_GoalRequiredHint"]   = "* Целевая сумма обязательна для копилки",
                ["Categories_DeleteConfirm"]   = "Удалить «{0}»? Записи с этой категорией получат пустую категорию.",
                ["Savings_NameLbl"]            = "Название:",
                ["Savings_BalanceLbl"]         = "Начальный баланс:",
                ["Savings_TargetLbl"]          = "Целевая сумма:",
                ["Savings_RateLbl"]            = "Ставка (% год):",
                ["Savings_ContribLbl"]         = "Взнос в месяц:",
                ["Savings_StartDateLbl"]       = "Дата открытия:",
                ["Savings_NotesLbl"]           = "Описание:",
                ["Savings_CanWithdraw"]        = "Можно снимать",
                ["Savings_SaveBtn"]            = "Сохранить",
                ["Savings_CancelBtn"]          = "Отмена",
                ["Savings_Deposit"]            = "Пополнить",
                ["Savings_Withdraw"]           = "Снять",
                ["Savings_Accrue"]             = "Начислить %",
                ["Savings_Archive"]            = "Архив",
                ["Savings_Delete"]             = "Удалить",
                ["Savings_History"]            = "История",
                ["Savings_ProjectedLbl"]       = "Прогноз через мес.:",
                ["Savings_ProgressLbl"]        = "Прогресс к цели:",
                ["Savings_TypeDeposit"]        = "Пополнение",
                ["Savings_TypeWithdraw"]       = "Снятие",
                ["Savings_TypeInterest"]       = "Проценты",
                ["Savings_AmountLbl"]          = "Сумма:",
                ["Savings_NoteLbl"]            = "Примечание:",
                ["Savings_DateLbl"]            = "Дата:",
                ["Savings_EmptyHint"]          = "Нет счетов. Нажмите «+ Счёт» или «+ Копилка» чтобы создать.",
                ["Savings_CurrentBalanceLbl"]  = "текущий баланс",
                ["Savings_GoalLbl"]            = "Цель:",
                ["Savings_GoalAchievedBadge"]  = "✅ Цель достигнута",
                ["Savings_RecurringPeriodLbl"] = "Периодичность пополнения:",
                ["Savings_RecurringAmountLbl"] = "Сумма пополнения:",
                ["Savings_PeriodNone"]         = "Нет",
                ["Savings_PeriodMonthly"]      = "Ежемесячно",
                ["Savings_PeriodQuarterly"]    = "Ежеквартально",
                ["Savings_PeriodYearly"]       = "Ежегодно",
                ["Savings_AutoContribNote"]    = "авто",
                ["Savings_GoalAchievedNotif"]  = "Поздравляем! Вы достигли цели «{0}» в размере {1:N0} ₽!",
                ["Savings_GoalAchievedTitle"]  = "Цель копилки достигнута 🎉",

                // Сводка — счета
                ["Summary_SavingsHeader"]      = "Счета / Копилки",
                ["Summary_SavingsTotal"]       = "Общий баланс:",
                ["Summary_SavingsCount"]       = "Счетов:",
                ["Summary_SavingsGoal"]        = "Прогресс к цели",

                // Гибкие уведомления
                ["NotifUnit_Minutes"]          = "мин",
                ["NotifUnit_Hours"]            = "ч",
                ["NotifUnit_Days"]             = "дн",
                ["NotifUnit_Weeks"]            = "нед",

                // Ежегодное повторение — год окончания
                ["RepeatUntilYear"]            = "Повторять до года:",

                // Вкладка Функции в настройках
                ["Settings_Functions"]         = "Функции",

                // Управление подпиской
                ["SubExpiredLbl"]        = "Подписка истекла",
                ["SubExpiresLbl"]        = "Активна до",
                ["SubRenewBtn"]          = "Продлить подписку",

                // Трекер привычек
                ["HabitTrackerLbl"]      = "Трекер привычек",
                ["HabitTrackerSub"]      = "Отслеживайте ежедневные привычки и серии",
                ["Habits"]               = "Привычки",
                ["Habit_Title"]          = "Трекер привычек",
                ["Habit_AddBtn"]         = "+ Привычка",
                ["Habit_EditBtn"]        = "✏",
                ["Habit_DeleteBtn"]      = "✕",
                ["Habit_ArchiveBtn"]     = "Архив",
                ["Habit_DoneBtn"]        = "✓ Выполнено",
                ["Habit_UndoneBtn"]      = "Отменить",
                ["Habit_NameLbl"]        = "Название:",
                ["Habit_DescLbl"]        = "Описание:",
                ["Habit_CategoryLbl"]    = "Категория:",
                ["Habit_IconLbl"]        = "Иконка:",
                ["Habit_ColorLbl"]       = "Цвет:",
                ["Habit_RepeatLbl"]      = "Повторение:",
                ["Habit_Repeat_Daily"]   = "Ежедневно",
                ["Habit_Repeat_Weekdays"]= "По дням недели",
                ["Habit_Repeat_PerWeek"] = "N раз в неделю",
                ["Habit_Repeat_PerMonth"]= "N раз в месяц",
                ["Habit_WeekDaysLbl"]    = "Дни недели:",
                ["Habit_TimesLbl"]       = "Количество раз:",
                ["Habit_SaveBtn"]        = "Сохранить",
                ["Habit_CancelBtn"]      = "Отмена",
                ["Habit_EmptyHint"]      = "Нет привычек. Нажмите «+ Привычка» чтобы создать.",
                ["Habit_SelectHint"]     = "Выберите привычку из списка",
                ["Habit_StreakLbl"]      = "Серия",
                ["Habit_BestStreakLbl"]  = "Лучшая серия",
                ["Habit_TotalLbl"]       = "Всего выполнений",
                ["Habit_TodayDone"]      = "Выполнено сегодня",
                ["Habit_CategoryAddBtn"] = "+ Категория",
                ["Habit_NewCatLbl"]      = "Новая категория:",
                ["Habit_HistoryLbl"]     = "История выполнений",
                ["Habit_HeatMapLbl"]     = "Календарь активности",
                ["Habit_NoHistory"]      = "Нет истории выполнений",
                ["Habit_StatTitle"]      = "Статистика",
                ["Habit_ActiveCount"]    = "Активных привычек:",
                ["Habit_TodayCount"]     = "Сегодня выполнено:",
                ["Habit_AllCats"]        = "Все категории",
                ["Habit_ArchiveTitle"]   = "Архивные привычки",
                ["Habit_AchievTitle"]    = "Достижения",
                ["Habit_Achiev_7days"]   = "🔥 7 дней подряд",
                ["Habit_Achiev_30days"]  = "💪 30 дней подряд",
                ["Habit_Achiev_90days"]  = "🏆 90 дней подряд",
                ["Habit_Achiev_100done"] = "💯 100 выполнений",
                ["Habit_StartDate"]      = "Начало:",
                ["Habit_CompletedToday"] = "✅ Выполнено сегодня",
                ["Habit_NotToday"]       = "Не выполнено",
                ["Habit_NameRequired"]   = "Введите название привычки",
                ["Habit_Days"]           = "дн.",
                ["Habit_SearchWatermark"]= "Поиск привычек...",
                // Месячная сетка
                ["Habit_MonthGrid"]      = "Месяц",
                ["Habit_PrevMonth"]      = "‹",
                ["Habit_NextMonth"]      = "›",
                ["Habit_LegendDone"]     = "Выполнено",
                ["Habit_LegendPartial"]  = "Частично",
                ["Habit_LegendNone"]     = "Не выполнено",
                // Вкладки детали
                ["Habit_TabActivity"]    = "Активность",
                ["Habit_TabMonth"]       = "Месяц",
                ["Habit_TabAchiev"]      = "Достижения",
                // Шаблоны
                ["Habit_TemplatesBtn"]   = "📋 Шаблон",
                ["Habit_TemplateTitle"]  = "Шаблоны привычек",
                ["Habit_UseTemplate"]    = "Использовать",
                ["Habit_SaveTemplate"]   = "Сохранить как шаблон",
                ["Habit_DeleteTemplate"] = "Удалить",
                ["Habit_SysTemplates"]   = "Предустановленные",
                ["Habit_MyTemplates"]    = "Мои шаблоны",
                ["Habit_TplEmpty"]       = "Нет пользовательских шаблонов",
                ["Habit_TplName"]        = "Название шаблона:",
                ["Habit_TplSaved"]       = "Шаблон сохранён",
                // Связанная задача
                ["Habit_LinkedTask"]     = "Связанная задача:",
                ["Habit_NoLinkedTask"]   = "— Без задачи —",
                // Экспорт
                ["Habit_ExportBtn"]      = "⬇ Экспорт",
                ["Habit_ExportCsv"]      = "Экспорт в CSV",
                ["Habit_ExportExcel"]    = "Экспорт в Excel",
                ["Habit_ExportDone"]     = "Сохранено:",
                ["Habit_ExportError"]    = "Ошибка экспорта",

                // Дополнительные модули (Промпт 1)
                ["Feat_AdditionalModulesCard"]   = "Дополнительные модули",
                ["Feat_AdditionalStatsCard"]     = "Дополнительная статистика",
                ["Feat_BackgroundSoundsLbl"]     = "Фоновые звуки",
                ["Feat_BackgroundSoundsSub"]     = "Воспроизведение эмбиент-звуков и своих аудио",
                ["Feat_MoodTrackerLbl"]          = "Трекер настроения",
                ["Feat_MoodTrackerSub"]          = "Отслеживание настроения и активностей",
                ["Feat_NotesAndDiaryLbl"]        = "Заметки и дневник",
                ["Feat_NotesAndDiarySub"]        = "Личные записи с привязкой к дням",
                ["Feat_WorkoutTrackerLbl"]       = "Трекер тренировок",
                ["Feat_WorkoutTrackerSub"]       = "Программы, упражнения, прогресс в зале",
                ["Feat_MediaTrackerLbl"]         = "Трекер медиа",
                ["Feat_MediaTrackerSub"]         = "Фильмы, сериалы, аниме, книги, манга",
                ["Feat_ExtendedStatsLbl"]        = "Расширенная статистика",
                ["Feat_ExtendedStatsSub"]        = "Годовой отчёт и сводка по всем модулям",
                ["Feat_ShowTodayStatsBtn"]       = "Показать статистику за сегодня",
                ["Feat_EnabledInSettings"]       = "Включить в Настройки → Функции",
                ["Feat_BaseModulesCard"]         = "Базовые модули",

                // Заметки и дневник
                ["Notes_Title"]           = "Заметки и дневник",
                ["Notes_NewBtn"]          = "+ Заметка",
                ["Notes_SearchWatermark"] = "Поиск по заметкам...",
                ["Notes_TagFilter"]       = "Тег:",
                ["Notes_AllTags"]         = "Все теги",
                ["Notes_PeriodFrom"]      = "С:",
                ["Notes_PeriodTo"]        = "По:",
                ["Notes_ClearFilter"]     = "Сбросить",
                ["Notes_TitleLbl"]        = "Заголовок:",
                ["Notes_TitleWatermark"]  = "Название заметки",
                ["Notes_DateLbl"]         = "Дата:",
                ["Notes_TagsLbl"]         = "Теги:",
                ["Notes_TagWatermark"]    = "Добавить тег и нажать Enter",
                ["Notes_ContentLbl"]      = "Содержимое:",
                ["Notes_SavedStatus"]     = "Сохранено",
                ["Notes_SavingStatus"]    = "Сохранение...",
                ["Notes_UnsavedStatus"]   = "Не сохранено",
                ["Notes_DeleteConfirm"]   = "Удалить эту заметку?",
                ["Notes_DeleteBtn"]       = "Удалить",
                ["Notes_ExportBtn"]       = "⬇ Экспорт",
                ["Notes_ExportMd"]        = "Экспорт в Markdown",
                ["Notes_ExportHtml"]      = "Экспорт в HTML",
                ["Notes_ExportTxt"]       = "Экспорт в TXT",
                ["Notes_ExportDone"]      = "Файл сохранён:",
                ["Notes_ExportError"]     = "Ошибка экспорта",
                ["Notes_EmptyHint"]       = "Нет заметок. Нажмите «+ Заметка» чтобы создать.",
                ["Notes_SelectHint"]      = "Выберите заметку или создайте новую",
                ["Notes_FmtBold"]         = "Жирный",
                ["Notes_FmtItalic"]       = "Курсив",
                ["Notes_FmtCode"]         = "Код",
                ["Notes_FmtH1"]           = "Заголовок 1",
                ["Notes_FmtH2"]           = "Заголовок 2",
                ["Notes_FmtQuote"]        = "Цитата",
                ["Notes_FmtList"]         = "Список",
                ["Notes_Badge"]           = "📝 Заметки: {0}",

                // Трекер настроения
                ["Mood_Title"]            = "Трекер настроения",
                ["Mood_NewBtn"]           = "+ Запись",
                ["Mood_SaveBtn"]          = "Сохранить",
                ["Mood_EditBtn"]          = "✏ Редактировать",
                ["Mood_DeleteBtn"]        = "Удалить",
                ["Mood_CancelBtn"]        = "Отмена",
                ["Mood_DeleteConfirm"]    = "Удалить эту запись?",
                ["Mood_EmptyHint"]        = "Нет записей. Нажмите «+ Запись» чтобы начать.",
                ["Mood_SelectHint"]       = "Выберите запись или создайте новую",
                ["Mood_DateLbl"]          = "Дата:",
                ["Mood_LevelLbl"]         = "Настроение:",
                ["Mood_Level1"]           = "Ужасно",
                ["Mood_Level2"]           = "Плохо",
                ["Mood_Level3"]           = "Так себе",
                ["Mood_Level4"]           = "Хорошо",
                ["Mood_Level5"]           = "Супер",
                ["Mood_ActivitiesLbl"]    = "Активности:",
                ["Mood_AddCustom"]        = "+ Своя",
                ["Mood_CommentLbl"]       = "Комментарий:",
                ["Mood_CommentWatermark"] = "Как прошёл день?",
                ["Mood_PhotosLbl"]        = "Фото:",
                ["Mood_AddPhotoBtn"]      = "+ Фото",
                ["Mood_AnalyticsTitle"]   = "Аналитика",
                ["Mood_PeriodWeek"]       = "Неделя",
                ["Mood_PeriodMonth"]      = "Месяц",
                ["Mood_PeriodYear"]       = "Год",
                ["Mood_AvgLabel"]         = "Среднее настроение",
                ["Mood_TotalLabel"]       = "Записей",
                ["Mood_DistribLabel"]     = "Распределение",
                ["Mood_YearGrid"]         = "Год в точках",
                ["Mood_FilterAll"]        = "Все",
                ["Mood_FilterMonth"]      = "Месяц",
                ["Mood_FilterYear"]       = "Год",
                ["Mood_FilterPeriod"]     = "Период:",
                ["Mood_SearchWatermark"]  = "Поиск по комментарию...",
                ["Mood_CustomNameLbl"]    = "Название:",
                ["Mood_ConfirmCustom"]    = "✓",
                ["Mood_MonthLabel"]       = "янв.;фев.;мар.;апр.;май;июн.;июл.;авг.;сен.;окт.;ноя.;дек."
            },
            ["English"] = new Dictionary<string, string>
            {
                // Settings window
                ["Settings"] = "Settings",
                ["General"] = "General",
                ["Notifications"] = "Notifications",
                ["Hotkeys"] = "Hotkeys",
                ["Data"] = "Data",
                ["Appearance"] = "🌙 Appearance",
                ["LightTheme"] = "Light",
                ["DarkTheme"] = "Dark",
                ["AutoTheme"] = "Auto",
                ["LangRegion"] = "🌐 Language & Region",
                ["SysNotif"] = "System Notifications",
                ["SysNotifSub"] = "Show system push notifications",
                ["SoundNotif"] = "Sound Notifications",
                ["SoundNotifSub"] = "Play audio on timer finish",
                ["SwitchToDay"] = "Switch to Day view",
                ["SwitchToWeek"] = "Switch to Week view",
                ["SwitchToMonth"] = "Switch to Month view",
                ["SwitchToYear"] = "Switch to Year view",
                ["GoToToday"] = "Go to Today",
                ["NewTask"] = "New Task",
                ["ExportData"] = "💾 Data Import & Export",
                ["Backup"] = "Backup data",
                ["BackupSub"] = "Create a secure backup of your DB",
                ["ExportBtn"] = "Export",
                ["ExportSuccess"] = "Data exported successfully!",
                ["ExportError"] = "Export error: ",
                ["DangerZone"] = "Danger Zone",
                ["ClearSub"] = "Permanent data wipe without recovery",
                ["ClearBtn"] = "Clear all data",
                ["ClearConfirm"] = "Are you sure? All data will be permanently deleted.",
                ["Yes"] = "Yes",
                ["No"] = "No",
                ["ClearSuccess"] = "All data has been cleared.",
                ["Close"] = "Close",
                ["Save"] = "Save",

                // Main window
                ["TitleDay"] = "Day",
                ["TitleWeek"] = "Week",
                ["TitleMonth"] = "Month",
                ["TitleYear"] = "Year",
                ["Tasks"] = "Tasks",
                ["Timer"] = "Timer",
                ["AnalyticsTitle"] = "Analytics",
                ["MoreBtn"] = "More Details",
                ["CustomSettings"] = "Custom Mode",
                ["FilterAll"] = "All",
                ["FilterHigh"] = "High",
                ["FilterMedium"] = "Medium",
                ["AddEventBtn"] = "+ Event",
                ["TodayBtn"] = "Today",

                ["AnalyticsSubtitle"] = "Detailed report for current period",
                ["FocusedTotal"] = "Total Focused",
                ["TasksCompleted"] = "Tasks Completed",
                ["Productivity"] = "Productivity",
                ["FocusDistributionWeek"] = "Focus distribution by weekdays",
                ["ProjectFocusCategories"] = "Focus by project categories",
                ["Done"] = "Done",
                ["LowLevel"] = "Low level",
                ["MediumLevel"] = "Medium level",
                ["HighLevel"] = "High level",

                ["PlanVsFactToday"] = "Plan vs Fact today",
                ["MoreDetails"] = "More Details",
                ["Plan"] = "Plan",
                ["Fact"] = "Fact",
                ["CustomMode"] = "Custom Mode",
                ["Week"] = "Week",
                ["HoursShort"] = "h",
                ["MinutesShort"] = "m",
                // FIXED: full units for DurationText ("30 min", "1 h 15 min")
                ["DurationMin"] = "min",
                ["DurationHour"] = "h",
                ["PerWeek"] = "per week",
                ["Deviation"] = "Deviation",
                ["NoProject"] = "No Project",

                // FIXED: new localization keys (filters, projects, done, completed tasks)
                ["AllProjectsLbl"] = "All Projects",
                ["AllFilter"] = "All",
                ["ActiveFilter"] = "Active",
                ["CompletedFilter"] = "Completed",
                ["DoneBtn"] = "Done",
                ["CompletedTasksHeader"] = "Completed Tasks",
                ["PrevWeekTip"] = "Previous week",
                ["NextWeekTip"] = "Next week",
                ["DeviationLabel"] = "Plan / Fact (today)",
                ["DeviationSubNoPlan"] = "No tasks today",
                ["DeviationSubUnder"] = "Under plan",
                ["DeviationSubOnTrack"] = "On track",

                // Pomodoro templates
                ["PomodoroTemplates"] = "Pomodoro Templates",
                ["SaveAsTemplate"] = "Save as template",
                ["TemplateName"] = "Template Name",
                ["WorkTime"] = "Work",
                ["BreakTime"] = "Break",

                // Creation windows
                ["TaskTitle"] = "Task Dialog",
                ["TaskNameLbl"] = "Task Title:",
                ["TaskDesc"] = "Description:",
                ["DueDateLabel"] = "Due Date:",
                ["PriorityLabel"] = "Priority:",
                ["TaskNameWatermark"] = "Enter task name",
                ["TaskDescWatermark"] = "Add description",
                ["HasDateOpt"] = "📅 Assign due date",
                ["IsTimeBoundOpt"] = "⏰ Bind to specific time",
                ["IsDurationOpt"] = "📊 Set planned duration",
                ["DurationLabel"] = "Duration (min):",
                ["FilterLow"] = "Low",
                ["ProjectLabel"] = "📁 Project:",
                ["EventTitle"] = "Event Dialog",
                ["AllDayLbl"] = "All Day",
                ["StartTimeLbl"] = "Start Time:",
                ["EndTimeLbl"] = "End Time:",
                ["HourLabel"] = "Hour:",
                ["MinLabel"] = "Min:",
                ["ColorLabel"] = "Color:",
                ["HexColorLabel"] = "HEX code:",
                ["WorkingDaysLbl"] = "Working days count:",
                ["OffDaysLbl"] = "Off days count:",
                ["CycleStartLabel"] = "Cycle start date:",
                ["IntervalLabel"] = "Interval (every N):",
                ["IntervalUnitLbl"] = "Interval Unit:",

                // Recurrence start day
                ["MonthlyDayLbl"] = "Day of month (1-31):",
                ["YearlyDayLbl"] = "Day:",
                ["YearlyMonthLbl"] = "Month (1-12):",
                ["RecurrenceStartDayHint"] = "Recurrence start day",

                // Recurrence type localization
                ["RecurrenceLbl"] = "Recurrence:",
                ["Recurrence_None"] = "No recurrence",
                ["Recurrence_Daily"] = "Daily",
                ["Recurrence_Weekdays"] = "Weekdays",
                ["Recurrence_Weekly"] = "Weekly (by day)",
                ["Recurrence_Monthly"] = "Monthly",
                ["Recurrence_Yearly"] = "Yearly",
                ["Recurrence_Shift"] = "Shift schedule (2/2)",
                ["Recurrence_Custom"] = "Custom interval",

                // Interval unit localization
                ["IntervalUnit_Days"] = "Days",
                ["IntervalUnit_Weeks"] = "Weeks",
                ["IntervalUnit_Months"] = "Months",

                // Weekday checkboxes
                ["Day_Mon"] = "Mon",
                ["Day_Tue"] = "Tue",
                ["Day_Wed"] = "Wed",
                ["Day_Thu"] = "Thu",
                ["Day_Fri"] = "Fri",
                ["Day_Sat"] = "Sat",
                ["Day_Sun"] = "Sun",

                // Recurrence end date label
                ["RepeatUntilLbl"] = "Repeat until",
                // FIXED (4.4): localized default timer name
                ["PomodoroDefault"] = "Pomodoro 25/5",
                // FIXED (4.1): watermark hints for EventDialog
                ["EventNameWatermark"] = "Enter event name",
                ["EventDescriptionWatermark"] = "Add description (optional)",
                ["HexColorWatermark"] = "Color hex code, e.g. #3B82F6",
                // FIXED (4.5): timer template management
                ["DeleteTemplateConfirm"] = "Delete this template?",
                ["TemplatesHeader"] = "Timer templates",

                // FIXED (Part 2-3): account, login, registration, subscription
                ["Account"] = "Account",
                ["LoginTitle"] = "Sign in to FocusFlow",
                ["LoginEmailLbl"] = "Email",
                ["LoginPasswordLbl"] = "Password",
                ["LoginBtn"] = "Sign in",
                ["RegisterLinkBtn"] = "Create account",
                ["ContinueWithoutSyncBtn"] = "Continue without sync",
                ["RegisterTitle"] = "Registration",
                ["RegisterUsernameLbl"] = "Username",
                ["RegisterConfirmPasswordLbl"] = "Confirm password",
                ["RegisterBtn"] = "Register",
                ["BackToLoginBtn"] = "Back to sign in",
                ["AuthFillAllFields"] = "Please fill in all fields",
                ["AuthEmailTaken"] = "A user with this email already exists",
                ["AuthInvalidCredentials"] = "Invalid email or password",
                ["AuthNotLoggedIn"] = "You are not signed in",
                ["AuthWrongPassword"] = "Current password is incorrect",
                ["PasswordsDontMatch"] = "Passwords do not match",
                ["PaymentInvalidPlan"] = "Unknown subscription plan",
                ["PerMonth"] = "mo",
                ["PerYear"] = "yr",
                ["SubscriptionRequiredTitle"] = "Sync unavailable",
                ["SubscriptionRequiredText"] = "Purchase a subscription to use sync and manage your account",
                ["BuyMonthBtn"] = "Buy monthly",
                ["BuyYearBtn"] = "Buy yearly",
                ["SubscriptionActiveLbl"] = "Subscription active until",
                ["DeveloperModeLbl"] = "Developer mode — free access",
                ["FreeAccessLbl"] = "Free access granted",
                ["SyncNowBtn"] = "Sync now",
                ["SyncEnabledLbl"] = "Use sync",
                ["LastSyncLbl"] = "Last sync",
                ["NeverLbl"] = "never",
                ["LogoutBtn"] = "Log out",
                ["EditProfileUsername"] = "Username",
                ["EditProfileEmail"] = "Email",
                ["ChangePasswordBtn"] = "Change password",
                ["CurrentPasswordLbl"] = "Current password",
                ["NewPasswordLbl"] = "New password",
                ["SyncingNowLbl"] = "Syncing...",
                ["SyncSuccessLbl"] = "Sync completed",
                ["SyncFailedLbl"] = "Sync failed — server unavailable",
                ["PostPurchaseTitle"] = "Subscription activated!",
                ["PostPurchaseText"] = "Create an account or sign in to an existing one to start syncing",
                ["AlreadyHaveAccountBtn"] = "I already have an account",
                ["CreateAccountBtn"] = "Create account",
                ["ChooseAvatarBtn"] = "Choose photo",
                ["RepeatUntilHint"] = "Select end date",

                // EventDialog hardcoded strings
                ["LoadTemplateHint"] = "Load from template:",
                ["ChooseTemplate"] = "Choose template...",
                ["EventNameLbl"] = "Name:",
                ["SaveAsTemplateLbl"] = "Save as template",
                ["TemplateNameWatermark"] = "Template name",
                ["TemplateHint"] = "Template will appear in template manager",
                ["DeleteBtn"] = "Delete",
                ["CancelBtn"] = "Cancel",
                ["SaveBtn"] = "Save",
                ["DaysLbl"] = "Days:",
                ["CycleStartLbl"] = "Cycle start:",
                ["IntervalLbl"] = "Interval (every N):",

                // Hotkeys descriptions
                ["HotkeyDay"] = "Switch to Day view",
                ["HotkeyWeek"] = "Switch to Week view",
                ["HotkeyMonth"] = "Switch to Month view",
                ["HotkeyYear"] = "Switch to Year view",
                ["HotkeyNewTask"] = "New Task",
                ["HotkeyToday"] = "Go to Today",

                // Notifications
                ["NotifEventTitle"] = "Event Reminder",
                ["NotifTimerTitle"] = "Timer Finished",
                ["NotifTimerBody"] = "Pomodoro session completed. Take a break!",
                ["MarkTaskOnTimerFinish"] = "Auto-complete task",
                ["MarkTaskOnTimerFinishSub"] = "Mark task as completed when all timer cycles finish",

                // Year calendar
                ["YearWord"] = "year",
                ["January"] = "January",
                ["February"] = "February",
                ["March"] = "March",
                ["April"] = "April",
                ["May"] = "May",
                ["June"] = "June",
                ["July"] = "July",
                ["August"] = "August",
                ["September"] = "September",
                ["October"] = "October",
                ["November"] = "November",
                ["December"] = "December",
                ["MonShort"] = "M",
                ["TueShort"] = "T",
                ["WedShort"] = "W",
                ["ThuShort"] = "T",
                ["FriShort"] = "F",
                ["SatShort"] = "S",
                ["SunShort"] = "S",

                // Hotkeys info
                ["HotkeyCtrl1"] = "Ctrl + 1",
                ["HotkeyCtrl2"] = "Ctrl + 2",
                ["HotkeyCtrlM"] = "Ctrl + M",
                ["HotkeyCtrlY"] = "Ctrl + Y",
                ["HotkeyCtrlN"] = "Ctrl + N",
                ["HotkeyCtrlT"] = "Ctrl + T",

                // Subtasks
                ["SubtasksLabel"]    = "Subtasks",
                ["SubtaskWatermark"] = "Subtask title",
                ["AddSubtaskBtn"]    = "+ Add subtask",

                // Timer completion dialog
                ["TimerDoneTitle"]       = "Timer finished",
                ["TimerDoneQuestion"]    = "Was the task completed?",
                ["TimerDoneOptions"]                = "What to do with the task?",
                ["TimerExtendLabel"]               = "Extend by",
                ["TimerExtendMinSuffix"]            = "min",
                ["TimerCompletion_ExtendWatermark"] = "Minutes",
                ["TimerExtendError"]               = "Enter a whole number ≥ 1",
                ["TimerExtendBtn"]                 = "Extend timer",
                ["TimerDeferBtn"]        = "Defer task",
                ["TimerDeleteTaskBtn"]   = "Delete task",

                // Event notification offset
                ["NotifTimeLbl"]         = "Remind me:",
                ["Notif_None"]           = "No reminder",
                ["Notif_10min"]          = "10 minutes before",
                ["Notif_30min"]          = "30 minutes before",
                ["Notif_1hour"]          = "1 hour before",
                ["Notif_1day"]           = "1 day before",
                ["NotifOffset_soon"]     = "starts soon",
                ["NotifOffset_30min"]    = "in 30 min",
                ["NotifOffset_1hour"]    = "in 1 hour",
                ["NotifOffset_1day"]     = "tomorrow",
                ["StartsNow"]            = "starts now",

                // Event copy
                ["CopyEventBtn"]         = "Copy to selected days",
                ["CopyEventTitle"]       = "Select days to copy to",
                ["CopyApplyBtn"]         = "Create copies",
                ["CopySelectedCount"]    = "Selected days:",
                ["CopySuccess"]          = "Event copies created",
                ["CopyPrevMonth"]        = "< Back",
                ["CopyNextMonth"]        = "Next >",

                // Finance module
                ["Finance"]              = "Finance",
                ["FinanceModuleLbl"]     = "Finance Module",
                ["FinanceModuleSub"]     = "Track income, expenses, subscriptions and loans",
                ["FinanceTab_Income"]    = "Income",
                ["FinanceTab_Expense"]   = "Expenses",
                ["FinanceTab_Sub"]       = "Subscriptions",
                ["FinanceTab_Loans"]     = "Loans",
                ["FinanceTab_Summary"]   = "Summary",
                ["Finance_AddIncome"]    = "+ Income",
                ["Finance_AddExpense"]   = "+ Expense",
                ["Finance_AddSub"]       = "+ Subscription",
                ["Finance_AddLoan"]      = "+ Loan",
                ["Finance_DateLbl"]      = "Date:",
                ["Finance_CategoryLbl"]  = "Category:",
                ["Finance_AmountLbl"]    = "Amount:",
                ["Finance_NoteLbl"]      = "Note:",
                ["Finance_NameLbl"]      = "Name:",
                ["Finance_CycleLbl"]     = "Billing cycle:",
                ["Finance_NextDateLbl"]  = "Next billing date:",
                ["Finance_PaidLbl"]      = "Paid",
                ["Finance_TotalLbl"]     = "Total amount:",
                ["Finance_RateLbl"]      = "Interest rate (% per year):",
                ["Finance_TermLbl"]      = "Term (months):",
                ["Finance_MonthlyLbl"]   = "Monthly payment:",
                ["Finance_RemainLbl"]    = "Remaining balance:",
                ["Finance_StartDateLbl"] = "Start date:",
                ["Finance_Balance"]      = "Balance",
                ["Finance_TotalIncome"]  = "Income this month",
                ["Finance_TotalExpense"] = "Expenses this month",
                ["Finance_Monthly"]      = "Monthly",
                ["Finance_Yearly"]       = "Yearly",
                ["Finance_ExportExcel"]  = "📊 Export to Excel",
                ["Finance_CalcPayment"]  = "Calculate",
                ["Finance_EditBtn"]      = "✏",
                ["Finance_DeleteBtn"]    = "✕",
                ["Finance_SaveBtn"]      = "Save",
                ["Finance_CancelBtn"]    = "Cancel",
                ["Finance_CatSalary"]    = "Salary",
                ["Finance_CatFreelance"] = "Freelance",
                ["Finance_CatOther"]     = "Other",
                ["Finance_CatFood"]      = "Food",
                ["Finance_CatTransport"] = "Transport",
                ["Finance_CatEntertain"] = "Entertainment",
                ["Finance_CatHealth"]    = "Health",
                ["Finance_CatHousing"]   = "Housing",
                ["Finance_CatStreaming"]  = "Streaming",
                ["Finance_CatSoftware"]  = "Software / Services",
                ["Finance_CatMortgage"]  = "Mortgage",
                ["Finance_CatCar"]       = "Car loan",
                ["Finance_CatConsumer"]        = "Consumer loan",
                ["Finance_AmountRequired"]     = "Please enter an amount greater than 0",
                ["Finance_AddCategory"]        = "+ Category",
                ["Finance_NewCategoryLbl"]     = "New category:",
                ["Finance_DownPaymentLbl"]     = "Down payment:",
                ["Finance_TermYearsLbl"]       = "Term (years):",
                ["Finance_NextPaymentLbl"]     = "Next payment:",
                ["Finance_EndDateLbl"]         = "End date:",
                ["Finance_NotifDaysLbl"]       = "Notify N days before:",
                ["Finance_EarlyRepayments"]    = "Early repayments",
                ["Finance_AddRepayment"]       = "+ Repayment",
                ["Finance_PaymentDue"]         = "payment in",
                ["Finance_EnabledInSettings"]  = "Enable in Settings → Features",

                // Empty-list hints
                ["Finance_IncomesEmptyHint"]   = "No income records. Click «+ Income» to add one.",
                ["Finance_ExpensesEmptyHint"]  = "No expenses. Click «+ Expense» to add one.",
                ["Finance_SubsEmptyHint"]      = "No subscriptions. Click «+ Subscription» to add one.",
                ["Finance_LoansEmptyHint"]     = "No loans. Click «+ Loan» to add one.",

                // History toggle
                ["Savings_ShowHistory"]        = "▼ History",
                ["Savings_HideHistory"]        = "▲ Hide history",

                // Summary — per-section stats
                ["Summary_IncomeCount"]        = "Records:",
                ["Summary_ExpenseCount"]       = "Records:",
                ["Summary_SubCount"]           = "Subscriptions:",
                ["Summary_SubMonthly"]         = "Monthly:",
                ["Summary_LoanCount"]          = "Loans:",
                ["Summary_LoanDebt"]           = "Total debt:",
                ["Summary_LoanMonthly"]        = "Monthly payment:",

                // Savings accounts
                ["FinanceTab_Savings"]         = "Savings/Jars",
                ["Savings_AddAccount"]         = "+ Account",
                ["Savings_AddGoal"]            = "+ Jar",
                ["Savings_NewAccount"]         = "New Account",
                ["Savings_NewGoal"]            = "New Jar",
                ["Savings_GoalBadge"]          = "🎯 Jar",
                ["Savings_GoalRequiredHint"]   = "* Target amount required for Jar",
                ["Categories_DeleteConfirm"]   = "Delete «{0}»? Records with this category will get an empty category.",
                ["Savings_NameLbl"]            = "Name:",
                ["Savings_BalanceLbl"]         = "Starting balance:",
                ["Savings_TargetLbl"]          = "Target amount:",
                ["Savings_RateLbl"]            = "Rate (% annual):",
                ["Savings_ContribLbl"]         = "Monthly contribution:",
                ["Savings_StartDateLbl"]       = "Open date:",
                ["Savings_NotesLbl"]           = "Description:",
                ["Savings_CanWithdraw"]        = "Allow withdrawals",
                ["Savings_SaveBtn"]            = "Save",
                ["Savings_CancelBtn"]          = "Cancel",
                ["Savings_Deposit"]            = "Deposit",
                ["Savings_Withdraw"]           = "Withdraw",
                ["Savings_Accrue"]             = "Accrue %",
                ["Savings_Archive"]            = "Archive",
                ["Savings_Delete"]             = "Delete",
                ["Savings_History"]            = "History",
                ["Savings_ProjectedLbl"]       = "Projected (1 month):",
                ["Savings_ProgressLbl"]        = "Progress to goal:",
                ["Savings_TypeDeposit"]        = "Deposit",
                ["Savings_TypeWithdraw"]       = "Withdrawal",
                ["Savings_TypeInterest"]       = "Interest",
                ["Savings_AmountLbl"]          = "Amount:",
                ["Savings_NoteLbl"]            = "Note:",
                ["Savings_DateLbl"]            = "Date:",
                ["Savings_EmptyHint"]          = "No accounts yet. Click «+ Account» or «+ Jar» to create one.",
                ["Savings_CurrentBalanceLbl"]  = "current balance",
                ["Savings_GoalLbl"]            = "Goal:",
                ["Savings_GoalAchievedBadge"]  = "✅ Goal achieved",
                ["Savings_RecurringPeriodLbl"] = "Recurring contributions:",
                ["Savings_RecurringAmountLbl"] = "Contribution amount:",
                ["Savings_PeriodNone"]         = "None",
                ["Savings_PeriodMonthly"]      = "Monthly",
                ["Savings_PeriodQuarterly"]    = "Quarterly",
                ["Savings_PeriodYearly"]       = "Yearly",
                ["Savings_AutoContribNote"]    = "auto",
                ["Savings_GoalAchievedNotif"]  = "Congratulations! You achieved your goal «{0}» with {1:N0} ₽!",
                ["Savings_GoalAchievedTitle"]  = "Savings goal achieved 🎉",

                // Summary — savings
                ["Summary_SavingsHeader"]      = "Accounts / Jars",
                ["Summary_SavingsTotal"]       = "Total balance:",
                ["Summary_SavingsCount"]       = "Accounts:",
                ["Summary_SavingsGoal"]        = "Progress to goal",

                // Flexible notifications
                ["NotifUnit_Minutes"]          = "min",
                ["NotifUnit_Hours"]            = "hr",
                ["NotifUnit_Days"]             = "days",
                ["NotifUnit_Weeks"]            = "wks",

                // Yearly recurrence end year
                ["RepeatUntilYear"]            = "Repeat until year:",

                // Features tab in settings
                ["Settings_Functions"]         = "Features",

                // Subscription management
                ["SubExpiredLbl"]        = "Subscription expired",
                ["SubExpiresLbl"]        = "Active until",
                ["SubRenewBtn"]          = "Renew subscription",

                // Habit Tracker
                ["HabitTrackerLbl"]      = "Habit Tracker",
                ["HabitTrackerSub"]      = "Track daily habits and streaks",
                ["Habits"]               = "Habits",
                ["Habit_Title"]          = "Habit Tracker",
                ["Habit_AddBtn"]         = "+ Habit",
                ["Habit_EditBtn"]        = "✏",
                ["Habit_DeleteBtn"]      = "✕",
                ["Habit_ArchiveBtn"]     = "Archive",
                ["Habit_DoneBtn"]        = "✓ Done",
                ["Habit_UndoneBtn"]      = "Undo",
                ["Habit_NameLbl"]        = "Name:",
                ["Habit_DescLbl"]        = "Description:",
                ["Habit_CategoryLbl"]    = "Category:",
                ["Habit_IconLbl"]        = "Icon:",
                ["Habit_ColorLbl"]       = "Color:",
                ["Habit_RepeatLbl"]      = "Repeat:",
                ["Habit_Repeat_Daily"]   = "Daily",
                ["Habit_Repeat_Weekdays"]= "Days of week",
                ["Habit_Repeat_PerWeek"] = "N times per week",
                ["Habit_Repeat_PerMonth"]= "N times per month",
                ["Habit_WeekDaysLbl"]    = "Week days:",
                ["Habit_TimesLbl"]       = "Times:",
                ["Habit_SaveBtn"]        = "Save",
                ["Habit_CancelBtn"]      = "Cancel",
                ["Habit_EmptyHint"]      = "No habits. Click «+ Habit» to create one.",
                ["Habit_SelectHint"]     = "Select a habit from the list",
                ["Habit_StreakLbl"]      = "Streak",
                ["Habit_BestStreakLbl"]  = "Best streak",
                ["Habit_TotalLbl"]       = "Total completions",
                ["Habit_TodayDone"]      = "Done today",
                ["Habit_CategoryAddBtn"] = "+ Category",
                ["Habit_NewCatLbl"]      = "New category:",
                ["Habit_HistoryLbl"]     = "Completion history",
                ["Habit_HeatMapLbl"]     = "Activity calendar",
                ["Habit_NoHistory"]      = "No completion history",
                ["Habit_StatTitle"]      = "Statistics",
                ["Habit_ActiveCount"]    = "Active habits:",
                ["Habit_TodayCount"]     = "Done today:",
                ["Habit_AllCats"]        = "All categories",
                ["Habit_ArchiveTitle"]   = "Archived habits",
                ["Habit_AchievTitle"]    = "Achievements",
                ["Habit_Achiev_7days"]   = "🔥 7 days in a row",
                ["Habit_Achiev_30days"]  = "💪 30 days in a row",
                ["Habit_Achiev_90days"]  = "🏆 90 days in a row",
                ["Habit_Achiev_100done"] = "💯 100 completions",
                ["Habit_StartDate"]      = "Started:",
                ["Habit_CompletedToday"] = "✅ Done today",
                ["Habit_NotToday"]       = "Not done",
                ["Habit_NameRequired"]   = "Please enter a habit name",
                ["Habit_Days"]           = "days",
                ["Habit_SearchWatermark"]= "Search habits...",
                // Monthly grid
                ["Habit_MonthGrid"]      = "Month",
                ["Habit_PrevMonth"]      = "‹",
                ["Habit_NextMonth"]      = "›",
                ["Habit_LegendDone"]     = "Done",
                ["Habit_LegendPartial"]  = "Partial",
                ["Habit_LegendNone"]     = "Not done",
                // Detail tabs
                ["Habit_TabActivity"]    = "Activity",
                ["Habit_TabMonth"]       = "Month",
                ["Habit_TabAchiev"]      = "Achievements",
                // Templates
                ["Habit_TemplatesBtn"]   = "📋 Template",
                ["Habit_TemplateTitle"]  = "Habit Templates",
                ["Habit_UseTemplate"]    = "Use",
                ["Habit_SaveTemplate"]   = "Save as template",
                ["Habit_DeleteTemplate"] = "Delete",
                ["Habit_SysTemplates"]   = "Predefined",
                ["Habit_MyTemplates"]    = "My templates",
                ["Habit_TplEmpty"]       = "No user templates",
                ["Habit_TplName"]        = "Template name:",
                ["Habit_TplSaved"]       = "Template saved",
                // Linked task
                ["Habit_LinkedTask"]     = "Linked task:",
                ["Habit_NoLinkedTask"]   = "— None —",
                // Export
                ["Habit_ExportBtn"]      = "⬇ Export",
                ["Habit_ExportCsv"]      = "Export to CSV",
                ["Habit_ExportExcel"]    = "Export to Excel",
                ["Habit_ExportDone"]     = "Saved:",
                ["Habit_ExportError"]    = "Export error",

                // Additional modules (Prompt 1)
                ["Feat_AdditionalModulesCard"]   = "Additional Modules",
                ["Feat_AdditionalStatsCard"]     = "Additional Statistics",
                ["Feat_BackgroundSoundsLbl"]     = "Background Sounds",
                ["Feat_BackgroundSoundsSub"]     = "Ambient audio playback and custom audio files",
                ["Feat_MoodTrackerLbl"]          = "Mood Tracker",
                ["Feat_MoodTrackerSub"]          = "Track your mood and daily activities",
                ["Feat_NotesAndDiaryLbl"]        = "Notes & Diary",
                ["Feat_NotesAndDiarySub"]        = "Personal entries linked to calendar days",
                ["Feat_WorkoutTrackerLbl"]       = "Workout Tracker",
                ["Feat_WorkoutTrackerSub"]       = "Programs, exercises and gym progress",
                ["Feat_MediaTrackerLbl"]         = "Media Tracker",
                ["Feat_MediaTrackerSub"]         = "Movies, series, anime, books and manga",
                ["Feat_ExtendedStatsLbl"]        = "Extended Statistics",
                ["Feat_ExtendedStatsSub"]        = "Annual report and summary across all modules",
                ["Feat_ShowTodayStatsBtn"]       = "Show today's statistics",
                ["Feat_EnabledInSettings"]       = "Enable in Settings → Features",
                ["Feat_BaseModulesCard"]         = "Core Modules",

                // Notes & Diary
                ["Notes_Title"]           = "Notes & Diary",
                ["Notes_NewBtn"]          = "+ Note",
                ["Notes_SearchWatermark"] = "Search notes...",
                ["Notes_TagFilter"]       = "Tag:",
                ["Notes_AllTags"]         = "All tags",
                ["Notes_PeriodFrom"]      = "From:",
                ["Notes_PeriodTo"]        = "To:",
                ["Notes_ClearFilter"]     = "Clear",
                ["Notes_TitleLbl"]        = "Title:",
                ["Notes_TitleWatermark"]  = "Note title",
                ["Notes_DateLbl"]         = "Date:",
                ["Notes_TagsLbl"]         = "Tags:",
                ["Notes_TagWatermark"]    = "Add tag and press Enter",
                ["Notes_ContentLbl"]      = "Content:",
                ["Notes_SavedStatus"]     = "Saved",
                ["Notes_SavingStatus"]    = "Saving...",
                ["Notes_UnsavedStatus"]   = "Unsaved",
                ["Notes_DeleteConfirm"]   = "Delete this note?",
                ["Notes_DeleteBtn"]       = "Delete",
                ["Notes_ExportBtn"]       = "⬇ Export",
                ["Notes_ExportMd"]        = "Export as Markdown",
                ["Notes_ExportHtml"]      = "Export as HTML",
                ["Notes_ExportTxt"]       = "Export as TXT",
                ["Notes_ExportDone"]      = "File saved:",
                ["Notes_ExportError"]     = "Export error",
                ["Notes_EmptyHint"]       = "No notes yet. Click «+ Note» to create one.",
                ["Notes_SelectHint"]      = "Select a note or create a new one",
                ["Notes_FmtBold"]         = "Bold",
                ["Notes_FmtItalic"]       = "Italic",
                ["Notes_FmtCode"]         = "Code",
                ["Notes_FmtH1"]           = "Heading 1",
                ["Notes_FmtH2"]           = "Heading 2",
                ["Notes_FmtQuote"]        = "Quote",
                ["Notes_FmtList"]         = "List",
                ["Notes_Badge"]           = "📝 Notes: {0}",

                // Mood Tracker
                ["Mood_Title"]            = "Mood Tracker",
                ["Mood_NewBtn"]           = "+ Entry",
                ["Mood_SaveBtn"]          = "Save",
                ["Mood_EditBtn"]          = "✏ Edit",
                ["Mood_DeleteBtn"]        = "Delete",
                ["Mood_CancelBtn"]        = "Cancel",
                ["Mood_DeleteConfirm"]    = "Delete this entry?",
                ["Mood_EmptyHint"]        = "No entries yet. Click «+ Entry» to get started.",
                ["Mood_SelectHint"]       = "Select an entry or create a new one",
                ["Mood_DateLbl"]          = "Date:",
                ["Mood_LevelLbl"]         = "Mood:",
                ["Mood_Level1"]           = "Awful",
                ["Mood_Level2"]           = "Bad",
                ["Mood_Level3"]           = "Okay",
                ["Mood_Level4"]           = "Good",
                ["Mood_Level5"]           = "Great",
                ["Mood_ActivitiesLbl"]    = "Activities:",
                ["Mood_AddCustom"]        = "+ Custom",
                ["Mood_CommentLbl"]       = "Comment:",
                ["Mood_CommentWatermark"] = "How was your day?",
                ["Mood_PhotosLbl"]        = "Photos:",
                ["Mood_AddPhotoBtn"]      = "+ Photo",
                ["Mood_AnalyticsTitle"]   = "Analytics",
                ["Mood_PeriodWeek"]       = "Week",
                ["Mood_PeriodMonth"]      = "Month",
                ["Mood_PeriodYear"]       = "Year",
                ["Mood_AvgLabel"]         = "Average mood",
                ["Mood_TotalLabel"]       = "Entries",
                ["Mood_DistribLabel"]     = "Distribution",
                ["Mood_YearGrid"]         = "Year in dots",
                ["Mood_FilterAll"]        = "All",
                ["Mood_FilterMonth"]      = "Month",
                ["Mood_FilterYear"]       = "Year",
                ["Mood_FilterPeriod"]     = "Period:",
                ["Mood_SearchWatermark"]  = "Search by comment...",
                ["Mood_CustomNameLbl"]    = "Name:",
                ["Mood_ConfirmCustom"]    = "✓",
                ["Mood_MonthLabel"]       = "Jan;Feb;Mar;Apr;May;Jun;Jul;Aug;Sep;Oct;Nov;Dec"
            }
        };

        // Применяем культуру при старте приложения
        var startCulture = GetCulture();
        CultureInfo.DefaultThreadCurrentCulture   = startCulture;
        CultureInfo.DefaultThreadCurrentUICulture = startCulture;
    }

    public string CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_translations.ContainsKey(value))
            {
                _currentLanguage = value;
                var ci = GetCulture();
                CultureInfo.DefaultThreadCurrentCulture   = ci;
                CultureInfo.DefaultThreadCurrentUICulture = ci;
                Thread.CurrentThread.CurrentCulture   = ci;
                Thread.CurrentThread.CurrentUICulture = ci;
                OnPropertyChanged(string.Empty);
            }
        }
    }

    public CultureInfo GetCulture() =>
        _currentLanguage == "English"
            ? new CultureInfo("en-GB")   // en-GB: день перед месяцем (18 June)
            : new CultureInfo("ru-RU");

    public string this[string key]
    {
        get
        {
            if (_translations.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var word))
                return word;
            return key;
        }
    }
}
